In [2]:
from contextuality.model import *
from contextuality.utils import *
from contextuality.functions import *

In [4]:
from test.test_functions import *
from test.test_model import *
from test.test_scenario import *

ModuleNotFoundError: No module named 'test.test_functions'

In [4]:
pr_box = pr_model()

In [5]:
print(pr_box)

         (0, 0) (0, 1) (1, 0) (1, 1)
(x1, x2) 0.5000 0.0000 0.0000 0.5000
(x2, x3) 0.5000 0.0000 0.0000 0.5000
(x3, x4) 0.5000 0.0000 0.0000 0.5000
(x4, x1) 0.0000 0.5000 0.5000 0.0000



In [6]:
tmp = Scenario([('x1','x2'),('x2','x3'),('x1','x3')], 2)

In [7]:
tmp.observables

['x1', 'x2', 'x3']

In [8]:
tmp.incidence_matrix

array([[1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 1]])

In [9]:
global_assigns = list(itertools.product(range(tmp.num_outcome), repeat=len(tmp.observables)))
print("possible global assignments: ", global_assigns)
local_assigns = list(itertools.product(range(tmp.num_outcome), repeat=len(tmp.contexts[2])))
print("possible local assignments: ", local_assigns)
print("example context: ", tmp.contexts[2])
ob_idx = [tmp.observables.index(ob) for ob in tmp.contexts[2]]
print("observable indices: ", ob_idx)
g_context = [tuple([g[idx] for idx in ob_idx]) for g in global_assigns]
print("global contexts: ", g_context)
M_context_this = numpy.zeros((len(local_assigns), len(global_assigns)), dtype=int)
for i in range(len(local_assigns)):
    for j in range(len(g_context)):
        M_context_this[i, j] = local_assigns[i] == g_context[j]
print(M_context_this)

possible global assignments:  [(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]
possible local assignments:  [(0, 0), (0, 1), (1, 0), (1, 1)]
example context:  ('x1', 'x3')
observable indices:  [0, 2]
global contexts:  [(0, 0), (0, 1), (0, 0), (0, 1), (1, 0), (1, 1), (1, 0), (1, 1)]
[[1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 1]]


In [10]:
dat = Scenario([['x1'],['x2'],['x3']], 2)
dat.incidence_matrix

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [46]:
emp1 = Model(Scenario([['x1'],['x2'],['x3']], 2), [[1/4,3/4],[3/5,2/5],[1/2,1/2]])
emp2 = Model(CyclicScenario(['x1','x2','x3'], 2),
                      [[1/2,0,0,1/2],
                       [1/2,0,0,1/2],
                       [0,1/2,1/2,0]])

In [104]:
print(emp1.vector)
print(emp2.vector)

[0.25 0.75 0.6  0.4  0.5  0.5 ]
[0.5        0.         0.         0.5        0.5        0.25
 0.         0.25       0.33333333 0.33333333 0.33333333 0.        ]


In [105]:
print(emp1.probability(['x1'],[1]))
print(emp2.probability(('x1','x2'),[1,1]))

0.75
0.5


In [106]:
print(emp1._decomposition('cf'))
print(emp2._decomposition('cf'))

1.0000000000406282
0.5


In [107]:
emp2.scenario.incidence_matrix

array([[1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1]])

In [108]:
emp2.vector

array([0.5       , 0.        , 0.        , 0.5       , 0.5       ,
       0.25      , 0.        , 0.25      , 0.33333333, 0.33333333,
       0.33333333, 0.        ])

In [31]:
problem = picos.Problem()
problem.options.solver = "mosek"

b = picos.RealVariable("b", 8)

In [47]:
M = emp2.scenario.incidence_matrix
v = emp2.vector
mode = 'sf'
num_global_assign = M.shape[1]
one = numpy.ones(num_global_assign)

problem = picos.Problem()
problem.options.solver = "mosek"

b = picos.RealVariable("b", num_global_assign)

problem.set_objective("max", one | b)

problem.add_constraint(M * b <= v)

if mode == "cf":
    problem.add_constraint(b >= 0)
if mode == "sf":
    problem.add_constraint(M * b >= 0)

solution = problem.solve()
weight_N = solution.value
print(weight_N)

1.0


In [48]:
print(emp2.contextual_fraction())
print(emp2.signalling_fraction())

1.0
0.0


In [49]:
emp2

'CF: 1.000000\nSF: 0.000000\nΔ: 0.000000\nCbD: 2.000000'

In [50]:
emp2.CbD_direct_influence()

0.0

In [114]:
emp2._distributions

array([[0.5       , 0.        , 0.        , 0.5       ],
       [0.5       , 0.25      , 0.        , 0.25      ],
       [0.33333333, 0.33333333, 0.33333333, 0.        ]])

In [51]:
emp2.CbD_measure()

2.0

In [116]:
emp2.summary()

'CF: 0.500000\nSF: 0.250000\nΔ: 1.166667\nCbD: -0.333333'

In [117]:
print(emp2)

         (0, 0) (0, 1) (1, 0) (1, 1)
(x1, x2) 0.5000 0.0000 0.0000 0.5000
(x2, x3) 0.5000 0.2500 0.0000 0.2500
(x3, x1) 0.3333 0.3333 0.3333 0.0000



In [6]:
ana_scenario = Scenario([('X','X'),('X','Z'),('Z','X'),('Z','Z')], 2)

In [14]:
ana_emp_model = Model(ana_scenario, [[1/2,0,0,1/2],
                                     [1/2,1/4,0,1/4],
                                     [1/3,1/3,1/3,0],
                                     [1/2,1/4,0,1/4]])

In [19]:
tmp = CyclicScenario(['a','b','A','B'],2)

In [25]:
tmp.contexts

[('a', 'b'), ('b', 'A'), ('A', 'B'), ('B', 'a')]

In [26]:
ana_scenario.contexts

[('X', 'X'), ('X', 'Z'), ('Z', 'X'), ('Z', 'Z')]

In [40]:
ana_emp_model.summary()

AssertionError: 